"""init_file

Revision ID: 440e17f2b25f
Revises:
Create Date: 2025-07-30 11:46:10.973141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "440e17f2b25f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("name", sa.Text(), nullable=False, comment="File's name"),
        sa.Column("reference", sa.Text(), nullable=True, comment="File's reference"),
        sa.Column(
            "reference_uuid",
            sa.UUID(),
            nullable=True,
            comment="Reference's uuid",
        ),
        sa.Column("bucket", sa.Text(), nullable=False, comment="File's bucket"),
        sa.Column("path", sa.Text(), nullable=False, comment="File's path"),
        sa.Column("mimetype", sa.Text(), nullable=False, comment="File's mimetype"),
        sa.Column(
            "jdata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
            comment="File's mimetype",
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
            comment="File's tags",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_files_reference"), "files", ["reference"], unique=False)
    op.create_index(
        op.f("ix_files_reference_uuid"),
        "files",
        ["reference_uuid"],
        unique=False,
    )
    op.create_index(op.f("ix_files_uuid"), "files", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_uuid"), table_name="files")
    op.drop_index(op.f("ix_files_reference_uuid"), table_name="files")
    op.drop_index(op.f("ix_files_reference"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
